# Application Configuration

spring:
  application:
    name: file-compression

server:
  port: 8081
  servlet:
    context-path: /api/v1/fc

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

# OpenAPI Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

# Logging Configuration
logging:
  level:
    com.regex.engine: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# Cors Configuration
cors:
  allowed-origins:
    - http://localhost:3333
    - http://localhost:3334
    - http://localhost:3335
    - http://localhost:3336
  allowed-methods:
    - GET
    - POST
    - PUT
    - PATCH
    - DELETE
    - OPTIONS
  allowed-headers:
    - "*"
  allow-credentials: true

# Async Configuration
async:
  core-pool-size: 4
  max-pool-size: 8
  queue-capacity: 100
  thread-name-prefix: CompressionAsync-
